### ISSUE TITLE
Bootstrap docker cannot populate DB

### ISSUE THREAD

**Issue by gitPr0bit** [ALFA-group/BRON#43]
Hi,
everytime I try to build everything using `docker-compose up -d` I end up with an empty DB. Looking at the logs of the 'bootstrap' container, I get:
```
2023-07-18 16:14:01,552 INFO: BEGIN Import BRON into Arangodb
Save data/attacks/technique_mitigation.jsonl 43
Save data/attacks/software.jsonl 635
Save data/attacks/technique_detection.jsonl 579
Save data/attacks/group.jsonl 136
Save data/attacks/software_technique_mapping.jsonl 8318
Save data/attacks/technique_mitigation_technique_mapping.jsonl 1156
Save data/attacks/group_technique_mapping.jsonl 3016
Save data/attacks/group_software_mapping.jsonl 830
Traceback (most recent call last):
  File "tutorials/build_bron.py", line 268, in <module>
    main(
  File "tutorials/build_bron.py", line 245, in main
    _arangodb(username, password, ip, no_validation)
  File "tutorials/build_bron.py", line 123, in _arangodb
    bron_arango.main(
  File "/usr/local/bron/graph_db/bron_arango.py", line 83, in main
    create_db(username, password, ip)
  File "/usr/local/bron/graph_db/bron_arango.py", line 174, in create_db
    if not sys_db.has_database(DB):
  File "/usr/local/lib/python3.8/site-packages/arango/database.py", line 773, in has_database
    return self._execute(request, response_handler)
  File "/usr/local/lib/python3.8/site-packages/arango/api.py", line 74, in _execute
    return self._executor.execute(request, response_handler)
  File "/usr/local/lib/python3.8/site-packages/arango/executor.py", line 68, in execute
    return response_handler(resp)
  File "/usr/local/lib/python3.8/site-packages/arango/database.py", line 770, in response_handler
    raise DatabaseListError(resp, request)
arango.exceptions.DatabaseListError: [HTTP 401][ERR 11] not authorized to execute this request
```
I tried to figure out by myself what's the problem, but I had no success. (The 'brondb' container seems to be ok, since I'm able to populate it from the host machine by running manually `python3 tutorials/build_bron.py --username=root --password=${BRON_PWD} --ip=${BRON_SERVER_IP}`)

**Comment by gitPr0bit** [comment]
I'm sorry, I just figured out that I had to run docker-compose as root.
