### ISSUE TITLE
Error start bootstrap container for BRON

### ISSUE THREAD

**Issue by lmarenast** [ALFA-group/BRON#50]
Hello, I am trying to run BRON with docker desktop, I have followed the step by step of the README, but running docker compose, the bootstrap container does not start, I get the following error, do you know why this is?
@
![Error BRON](https://github.com/ALFA-group/BRON/assets/61100693/f15380fb-e80b-4e71-9b98-f56b90e10f2b)

2024-06-28 15:34:00 bootstrap.sh: line 2: $'\r': command not found
2024-06-28 15:34:00 bootstrap.sh: line 5: $'\r': command not found
2024-06-28 15:34:00 Traceback (most recent call last):
2024-06-28 15:34:00   File "tutorials/build_bron.py", line 22, in <module>
2024-06-28 15:34:00     from offense.build_software_and_groups import build_software_and_groups, SG_OUT_DATA_DIR
2024-06-28 15:34:00   File "/usr/local/bron/offense/build_software_and_groups.py", line 13, in <module>
2024-06-28 15:34:00     from utils.mitigation_utils import (
2024-06-28 15:34:00   File "/usr/local/bron/utils/mitigation_utils.py", line 11, in <module>
2024-06-28 15:34:00     from graph_db.bron_arango import (
2024-06-28 15:34:00   File "/usr/local/bron/graph_db/bron_arango.py", line 174, in <module>
2024-06-28 15:34:00     def get_edge_document(o_edge: Tuple[str, str], validation: bool, schemas: dict[str, Any]) -> Tuple[Dict[str, str], str]:
2024-06-28 15:34:00 TypeError: 'type' object is not subscriptable

**Comment by hembergerik** [comment]
It should come from a typo in the type annotation for `get_edge_document` `dict`
